defaultEntryPoints = ["http","https"]
    logLevel = "INFO"
    [entryPoints]
      [entryPoints.http]
        address = ":80"
        compress = true

      [entryPoints.https]
        address = ":443"
        compress = true
        [entryPoints.https.tls]
          [entryPoints.https.tls.defaultCertificate]
          certFile = "/cert.pem"
          keyFile = "/key.pem"

      [entryPoints.dashboard]
        address = ":8081"

    [api]
      entryPoint = "dashboard"

    [docker]
      swarmMode = true
      exposedByDefault = false

    [traefikLog]
      filePath = "/logs/traefik.log"
      format   = "json"

    [accessLog]
      filePath = "/logs/access.log"
      format = "json"